server:
  port: 8093
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://localhost:3306/ebean?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      connection-timeout: 30000
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
ebean:
  search:
    jars: entity-core.jar